tinyMCE.addI18n('en.table_dlg',{
general_tab:"Основные",
advanced_tab:"Расширенные",
general_props:"Свойства",
advanced_props:"Расширенные свойства",
rowtype:"Строка в части таблицы",
title:"Вставить/изменить таблицу",
width:"Ширина",
height:"Высота",
cols:"Столбцы",
rows:"Строки",
cellspacing:"Расстояние между ячейками",
cellpadding:"Отступ от края ячейки",
border:"Граница",
align:"Выравнивание",
align_default:"По умолчанию",
align_left:"По левому краю",
align_right:"По правому краю",
align_middle:"По центру",
row_title:"Свойства строки",
cell_title:"Свойства ячейки",
cell_type:"Тип ячейки",
valign:"Выравнивание по высоте",
align_top:"По верхнему краю",
align_bottom:"По нижнему краю",
bordercolor:"Цвет границы",
bgcolor:"Цвет фона",
merge_cells_title:"Объединить ячейки",
id:"Идентификатор",
style:"Стиль",
langdir:"Направление текста",
langcode:"Код языка",
mime:"MIME тип",
ltr:"Слева направо",
rtl:"Справо налево",
bgimage:"Фоновое изображение",
summary:"Заключение",
td:"Данные",
th:"Заголовок",
cell_cell:"Обновить текущую ячейку",
cell_row:"Обновить все ячейки",
cell_all:"Обновить все ячейки",
row_row:"Обновить текущую строку",
row_odd:"Обновить нечетные строки",
row_even:"Обновить четные строки",
row_all:"Обновить все строки",
thead:"Заголовок таблицы",
tbody:"Тело таблицы",
tfoot:"Низ таблицы",
scope:"Зона",
rowgroup:"Группа строк",
colgroup:"Группа столбцов",
col_limit:"Вы превысили максимальное число столбцов ({$cols}).",
row_limit:"Вы превысили максимальное число строк ({$rows}).",
cell_limit:"Вы превысили максимальное число ячеек ({$cells}).",
missing_scope:"Прододлжить?",
caption:"Заголовок таблицы",
frame:"Рамка",
frame_none:"нет",
frame_groups:"группы",
frame_rows:"строки",
frame_cols:"столбцы",
frame_all:"все",
rules:"Линии",
rules_void:"нет",
rules_above:"верхняя",
rules_below:"нижняя",
rules_hsides:"справа и слева",
rules_lhs:"lhs",
rules_rhs:"rhs",
rules_vsides:"сверху и снизу",
rules_box:"со всехсторон",
rules_border:"граница"
});