tinyMCE.addI18n('en.advanced',{
style_select:"Стили",
font_size:"Размер шрифта",
fontdefault:"Шрифт",
block:"Стиль",
paragraph:"Обычный",
div:"Div",
address:"Address",
pre:"Preformatted",
h1:"Заголовок 1",
h2:"Заголовок 2",
h3:"Заголовок 3",
h4:"Заголовок 4",
h5:"Heading 5",
h6:"Heading 6",
blockquote:"Blockquote",
code:"Code",
samp:"Code sample",
dt:"Definition term ",
dd:"Definition description",
bold_desc:"Жирный (Ctrl+B)",
italic_desc:"Курсив (Ctrl+I)",
underline_desc:"Underline (Ctrl+U)",
striketrough_desc:"Зачеркнутый",
justifyleft_desc:"По левому краю",
justifycenter_desc:"По центру",
justifyright_desc:"По правому краю",
justifyfull_desc:"Align full",
bullist_desc:"Маркерованный список",
numlist_desc:"Нумерованный список",
outdent_desc:"Уменьшить отступ",
indent_desc:"Увеличить отступ",
undo_desc:"Отменить (Ctrl+Z)",
redo_desc:"Вернуть (Ctrl+Y)",
link_desc:"Вставить/изменить ссылку",
unlink_desc:"Удалить ссылку",
image_desc:"Вставить/изменить изображение",
cleanup_desc:"Очистить код",
code_desc:"Редактировать HTML",
sub_desc:"Подстрочный",
sup_desc:"Надстрочный",
hr_desc:"Горизонтальная линия",
removeformat_desc:"Очистить форматирование",
custom1_desc:"Your custom description here",
forecolor_desc:"Цвет текста",
backcolor_desc:"Цвет фона",
charmap_desc:"Символ",
visualaid_desc:"Toggle guidelines/invisible elements",
anchor_desc:"Insert/edit anchor",
cut_desc:"Cut",
copy_desc:"Copy",
paste_desc:"Paste",
image_props_desc:"Свойства изображения",
newdocument_desc:"New document",
help_desc:"Help",
blockquote_desc:"Blockquote",
clipboard_msg:"Ваш браузер не поддерживает эту операцию. Нажмите CTRL+V, чтобы вставить текст.",
path:"Path",
newdocument:"Are you sure you want clear all contents?",
toolbar_focus:"Jump to tool buttons - Alt+Q, Jump to editor - Alt-Z, Jump to element path - Alt-X",
more_colors:"More colors"
});