tinyMCE.addI18n('en.advanced_dlg',{
code_title:"Редактирование HTML",
code_wordwrap:"Переносить по словам",
charmap_title:"Выберите символ",
image_title:"Вставить/изменить изображение",
image_src:"Адрес",
image_alt:"Описание",
image_list:"Выбрать",
image_upload:"Закачать",
image_border:"Граница",
image_dimensions:"Размеры",
image_vspace:"Отступ по вертикали",
image_hspace:"Отступ по горизонтали",
image_align:"Выравнивание",
image_align_baseline:"По центру",
image_align_top:"По верху",
image_align_middle:"По середине",
image_align_bottom:"По низу",
image_align_texttop:"По верху текста",
image_align_textbottom:"По ниху текста",
image_align_left:"По левому краю",
image_align_right:"По правому краю",
link_title:"Вставить/изменить ссылку",
link_url:"Адрес",
link_target:"Окно",
link_target_same:"Открыть в текущем окне",
link_target_blank:"Открыть в новом окне",
link_titlefield:"Подсказка",
link_is_email:"Ссылка является e-mail адресом?",
link_is_external:"Ссылка на внешний сайт?",
link_list:"Страницы"
});